# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Copy test build logs
        run: cp -r .github/data/* .

      - name: Create and show warnings report
        uses: ./
        with:
          build-logs: |
            GCC*.log
            Clang_*.log
            llvm-19_release_build.log
          pr-comment-header: Ubuntu warnings report
          artifact-name: WarningsReportUbuntu

  test-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Copy test build logs
        run: cp -r .github/data/* .

      - name: Create and show warnings report
        uses: ./
        with:
          build-logs: |
            clang-cl*.log
            MSVC*.log
          pr-comment-header: Windows warnings report
          artifact-name: WarningsReportWindows
